server:
  port: 8000

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /product-service/**
      service-id: product-service
      stripPrefix: true
    offer-service:
      path: /offer-service/**
      serviceId: offer-service
      stripPrefix: true

product-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8180
    ServerListRefreshInterval: 15000

offer-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082
    ServerListRefreshInterval: 15000

endpoints:
  routes:
    sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/